In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/spaceship-titanic/sample_submission.csv
/kaggle/input/competitions/spaceship-titanic/train.csv
/kaggle/input/competitions/spaceship-titanic/test.csv

In [2]:
train=pd.read_csv("/kaggle/input/competitions/spaceship-titanic/train.csv")
test=pd.read_csv("/kaggle/input/competitions/spaceship-titanic/test.csv")

In [3]:
train.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [4]:
train.info()
print(train.shape)
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB
(8693, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB
None

In [5]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [6]:
x=train.drop(["Transported","PassengerId","Name"],axis=1)
y=train["Transported"]

In [7]:
y

0       False
1        True
2       False
3       False
4        True
        ...
8688    False
8689    False
8690     True
8691    False
8692     True
Name: Transported, Length: 8693, dtype: bool

In [8]:
test_data=test.drop(["PassengerId","Name"],axis=1)

In [9]:
full=pd.concat([x,test_data],axis=0)

In [10]:
full

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
4272,Earth,True,G/1496/S,TRAPPIST-1e,34.0,False,0.0,0.0,0.0,0.0,0.0
4273,Earth,False,NaN,TRAPPIST-1e,42.0,False,0.0,847.0,17.0,10.0,144.0
4274,Mars,True,D/296/P,55 Cancri e,NaN,False,0.0,0.0,0.0,0.0,0.0
4275,Europa,False,D/297/P,NaN,NaN,False,0.0,2680.0,0.0,0.0,523.0
4276,Earth,True,G/1498/S,PSO J318.5-22,43.0,False,0.0,0.0,0.0,0.0,0.0

In [11]:
full.shape

(12970, 11)

In [12]:
full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12970 entries, 0 to 4276
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    12682 non-null  object
 1   CryoSleep     12660 non-null  object
 2   Cabin         12671 non-null  object
 3   Destination   12696 non-null  object
 4   Age           12700 non-null  float64
 5   VIP           12674 non-null  object
 6   RoomService   12707 non-null  float64
 7   FoodCourt     12681 non-null  float64
 8   ShoppingMall  12664 non-null  float64
 9   Spa           12686 non-null  float64
 10  VRDeck        12702 non-null  float64
dtypes: float64(6), object(5)
memory usage: 1.2+ MB

In [13]:
num_col=full.select_dtypes(include=["float64"]).columns

In [14]:
num_col

Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='object')

In [15]:
for col in num_col:
    full[col] = full[col].fillna(full[col].median())

In [16]:
full.isnull().sum()

HomePlanet      288
CryoSleep       310
Cabin           299
Destination     274
Age               0
VIP             296
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
dtype: int64

In [17]:
full["Cabin"]

0          B/0/P
1          F/0/S
2          A/0/S
3          A/0/S
4          F/1/S
          ...
4272    G/1496/S
4273         NaN
4274     D/296/P
4275     D/297/P
4276    G/1498/S
Name: Cabin, Length: 12970, dtype: object

In [18]:
full["VIP"]=full["VIP"].map({True:1, False: 0})

In [19]:
full["CryoSleep"] = full["CryoSleep"].map({True: 1, False: 0})

In [20]:
full["VIP"].unique()

full["CryoSleep"].unique()

array([ 0.,  1., nan])

In [21]:
full["CryoSleep"].value_counts(dropna=False)

CryoSleep
0.0    8079
1.0    4581
NaN     310
Name: count, dtype: int64

In [22]:
full["VIP"] = full["VIP"].fillna(0)

full["CryoSleep"] = full["CryoSleep"].fillna(0)

In [23]:
full["VIP"].isnull().sum()

full["CryoSleep"].isnull().sum()

np.int64(0)

In [24]:
cat_cols = full.select_dtypes(include=["object"]).columns

for col in cat_cols:
    full[col] = full[col].fillna(full[col].mode()[0])

In [25]:
full[cat_cols].isnull().sum()

HomePlanet     0
Cabin          0
Destination    0
dtype: int64

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
for col in cat_cols:
    full[col]=encoder.fit_transform(full[col])

In [27]:
full.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,1,0.0,208,2,39.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.0,3241,2,24.0,0.0,109.0,9.0,25.0,549.0,44.0
2,1,0.0,1,2,58.0,1.0,43.0,3576.0,0.0,6715.0,49.0
3,1,0.0,1,2,33.0,0.0,0.0,1283.0,371.0,3329.0,193.0
4,0,0.0,3243,2,16.0,0.0,303.0,70.0,151.0,565.0,2.0

In [28]:
X = full[:len(train)]

X_test = full[len(train):]

In [29]:
print(X.shape)

print(X_test.shape)

print(y.shape)

(8693, 11)
(4277, 11)
(8693,)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [31]:
print(X_train.shape)

X_valid.shape

(6954, 11)

(1739, 11)

In [32]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

In [33]:
preds=model.predict(X_valid)

In [34]:
from sklearn.metrics import accuracy_score

accuracy_score(y_valid, preds)

0.7757331799884991

In [35]:
test_preds = model.predict(X_test)

In [36]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Transported": test_preds
})

submission.head()

  PassengerId  Transported
0     0013_01        False
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01        False

In [37]:
submission.to_csv("submission.csv", index=False)